svc:
  - name: wrangling-service
    namespace: default
    docker_image: nginx:latest
    replicas: 1
    svcPort: 80
    targetPort: 80
    imagePullPolicy : Always
    # path_check: "html"
    tls_secret: ""
    host : "wrangling-service.24.199.74.71.nip.io"
    apiPrefix: "/"
    resources:
      memoryMiB: 300
      cpuMilli: 300
    env:
    # - name: "NODE_ENV"
    #   value: "production"

  
#