name: API Build, Push, Install 

on:
  push:
    branches: main
    paths:
      - 'web-procycla-api/**'
      - 'helm-charts/generic/api-values.yaml'
      - '.github/workflows/api.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Build image 
        run: 
          docker build -t ${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/api:latest -f ./web-procycla-api/Dockerfile ./web-procycla-api

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
        
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_K8S_ID }} 

      - name: Push image to DO Container Registry 
        run: docker push ${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/api:latest

      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade api helm-charts/generic/apps --install --wait --atomic --namespace=default --values=helm-charts/generic/api-values.yaml --set "svc[0].docker_image=${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/api:latest"
          #