{{- range  .Values.svc }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .name }}-ingress"
  namespace: {{ .namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
     # nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"

    # nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   more_set_headers "X-Forwarded-Proto: https";
spec:
  # tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  # - hosts:
  #   - "{{ .host}}"
  #   secretName: "tls-secret" # < cert-manager will store the created ce
  rules:
  - host: "{{ .host}}"
    http:
      paths:
      - path: "{{ .apiPrefix}}" 
        pathType: Prefix
        backend:
          service:
            name: {{ .name }}-svc
            port: 
              number: {{ .svcPort}}

{{- end }}